# Generated by Django 2.2.1 on 2019-05-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisticos',
            name='attractions',
            field=models.ManyToManyField(to='atracoes.Atracoes'),
        ),
    ]
