# Generated by Django 2.2.1 on 2019-05-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliations', '0001_initial'),
        ('comments', '0001_initial'),
        ('core', '0002_pontosturisticos_attractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisticos',
            name='assessments',
            field=models.ManyToManyField(to='avaliations.Avaliacoes'),
        ),
        migrations.AddField(
            model_name='pontosturisticos',
            name='comments',
            field=models.ManyToManyField(to='comments.Comentarios'),
        ),
    ]
